site_name: Aphodite SASS
theme:
  name: material
  palette: 
    scheme: default
    primary: red
    accent: indigo
  features:
    - content.code.copy
    - content.code.annotate 
  icon:
    repo: fontawesome/brands/github
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/ildug/aphrodite-sass
repo_name: ildug/aphrodite-sass